<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tumblr.html</string>
	</array>
	<key>firstLineMatch</key>
	<string>^Type: Regular \(HTML\)</string>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--\s*&gt;)
		|\{\{?(if|foreach|capture|literal|foreach|php|section|strip)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^(?!.*?&lt;!--).*?--\s*&gt;
		|\{\{?/(if|foreach|capture|literal|foreach|php|section|strip)
		|^[^{]*\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>Tumblr</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.tumblr</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.tumblr</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.tumblr</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([Tt]itle|[Dd]ate|[Bb]asename|[Ss]lug|[Kk]eywords|[Bb]log|[Tt]ype|[Ll]ink|[Pp]ost|[Tt]ags|[Cc]omments|[Pp]ings?|[Cc]ategory|[Ss]tatus|[Ff]ormat)(:)\s*(.*)$\n?</string>
			<key>name</key>
			<string>meta.header.tumblr</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^([A-Za-z0-9]+):\s*(.*)$\n?</string>
			<key>name</key>
			<string>invalid.illegal.meta.header.tumblr</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?![A-Za-z0-9]+:)</string>
			<key>end</key>
			<string>^(?=not)possible$</string>
			<key>name</key>
			<string>text.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^✂-[✂-]+$\n</string>
					<key>name</key>
					<string>meta.separator.tumblr</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(Main entry text \w+)</string>
					<key>name</key>
					<string>keyword.other.tumblr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tumblr.html</string>
	<key>uuid</key>
	<string>67AAF08F-8182-4C2C-8755-43A64900CCE1</string>
</dict>
</plist>
